name: claims

services:
  claims_backend:
    build: ./backend
    container_name: claims_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    secrets:
      - mysql_password
      - secret_key
      - mysql_host
      - mysql_user
      - mysql_db
    environment:
      - MYSQL_HOST_FILE=/run/secrets/mysql_host
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DB_FILE=/run/secrets/mysql_db
      - SECRET_KEY_FILE=/run/secrets/secret_key
    networks:
      - claims

  claims_frontend:
    build: ./frontend
    container_name: claims_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - claims_backend
    networks:
      - claims

networks:
  claims:
    name: claims
    driver: bridge

secrets:
  mysql_password:
    file: ./secrets/mysql_password
  secret_key:
    file: ./secrets/secret_key
  mysql_host:
    file: ./secrets/mysql_host
  mysql_user:
    file: ./secrets/mysql_user
  mysql_db:
    file: ./secrets/mysql_db
