name: claimed

services:
  claimed_backend:
    build: ./backend
    container_name: claimed_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    secrets:
      - mysql_password
      - secret_key
      - mysql_host
      - mysql_user
      - mysql_db
    environment:
      - MYSQL_HOST_FILE=/run/secrets/mysql_host
      - MYSQL_USER_FILE=/run/secrets/mysql_user
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DB_FILE=/run/secrets/mysql_db
      - SECRET_KEY_FILE=/run/secrets/secret_key
    networks:
      - claimed
      - production

  claimed_frontend:
    build: ./frontend
    container_name: claimed_frontend
    restart: unless-stopped
    env_file:
      - ./fronted/.env
    depends_on:
      - claimed_backend
    networks:
      - claimed
      - production

networks:
  claimed:
    name: claimed
    driver: bridge
  production:
    external: true

secrets:
  mysql_password:
    file: ./secrets/mysql_password
  secret_key:
    file: ./secrets/secret_key
  mysql_host:
    file: ./secrets/mysql_host
  mysql_user:
    file: ./secrets/mysql_user
  mysql_db:
    file: ./secrets/mysql_db
